"""Add media_url to Reel

Revision ID: a33eaff9b6a6
Revises: 
Create Date: 2025-11-11 12:12:01.115657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33eaff9b6a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('comments_count')
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('title')
        batch_op.drop_column('views')
        batch_op.drop_column('likes')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.INTEGER(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('caption')
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
